public class TipsGenerator {
    public String suggestTips(double predictedBill) {
        String tips = "Tips to reduce your electricity consumption:\n";
        if (predictedBill > 0 && predictedBill <= 1000) {
            tips += "- Turn off lights and unplug devices when not in use.\n";
            tips += "- Opt for natural lighting during the day.\n";
            tips += "- Use a programmable thermostat to control heating and cooling.\n";
            tips += "- Set your computer to sleep mode when not in use.\n";
            tips += "- Hand wash dishes instead of using the dishwasher for small loads.\n";
            tips += "- Air dry clothes instead of using a dryer.\n";
            tips += "- Close curtains or blinds during hot days to keep the house cool.\n";
            tips += "- Use power strips to easily turn off multiple devices at once.\n";
            tips += "- Seal gaps around doors and windows to prevent drafts.\n";
            tips += "- Invest in energy-efficient appliances.\n";
            tips += "- Turn off and unplug electronics when going on vacation.\n";
            tips += "- Replace incandescent bulbs with LED or CFL bulbs.\n";
            tips += "- Use a microwave instead of a conventional oven for small meals.\n";
            tips += "- Keep refrigerator coils clean for efficient operation.\n";
            tips += "- Use a ceiling fan to supplement air conditioning.\n";
        } else if (predictedBill > 1000 && predictedBill <= 2000) {
            tips += "- Use energy-efficient appliances and LED bulbs.\n";
            tips += "- Adjust your air conditioning temperature to an energy-saving level.\n";
            tips += "- Insulate windows and doors to keep the house well-insulated.\n";
            tips += "- Plant shade trees around your home to reduce cooling costs.\n";
            tips += "- Wash clothes in cold water to save energy on heating.\n";
            tips += "- Use a slow cooker for cooking to save energy.\n";
            tips += "- Choose a laptop over a desktop computer for lower power consumption.\n";
            tips += "- Install a low-flow showerhead to conserve water and energy.\n";
            tips += "- Keep your freezer full to maximize energy efficiency.\n";
            tips += "- Replace air filters regularly for efficient HVAC performance.\n";
            tips += "- Use a power-saving mode on your gaming console.\n";
            tips += "- Unplug chargers and electronics when not in use.\n";
            tips += "- Use natural ventilation instead of air conditioning on mild days.\n";
            tips += "- Avoid using the oven during peak heat hours.\n";
            tips += "- Conduct a home energy audit to identify areas for improvement.\n";
        } else if (predictedBill > 2000 && predictedBill <= 3000) {
            tips += "- Install solar panels to generate renewable energy.\n";
            tips += "- Upgrade to energy-efficient windows and doors.\n";
            tips += "- Use a clothesline instead of a dryer for drying clothes.\n";
            tips += "- Consider investing in energy-efficient appliances.\n";
            tips += "- Reduce air leaks in your home by sealing gaps and cracks.\n";
            tips += "- Opt for natural ventilation instead of air conditioning when possible.\n";
            tips += "- Install a smart thermostat for precise temperature control.\n";
            tips += "- Use task lighting for specific areas instead of overhead lights.\n";
            tips += "- Turn off lights when leaving a room.\n";
            tips += "- Take shorter showers to conserve hot water.\n";
            tips += "- Use a laptop or tablet instead of a desktop computer.\n";
            tips += "- Run your dishwasher and washing machine with full loads only.\n";
            tips += "- Avoid using space heaters as they consume a lot of electricity.\n";
            tips += "- Use a microwave to defrost frozen food instead of hot water.\n";
            tips += "- Set your water heater temperature to 120 degrees Fahrenheit.\n";
        } else if (predictedBill > 3000 && predictedBill <= 4000) {
            tips += "- Plant trees around your house for shade and energy conservation.\n";
            tips += "- Use a water heater timer to reduce energy consumption.\n";
            tips += "- Consider using motion sensor lights for outdoor areas.\n";
            tips += "- Conduct an energy audit to identify areas for improvement.\n";
            tips += "- Use a slow cooker for cooking to save energy.\n";
            tips += "- Invest in an energy-efficient refrigerator.\n";
            tips += "- Use a smart power strip to automatically turn off idle electronics.\n";
            tips += "- Implement a rainwater harvesting system for watering plants.\n";
            tips += "- Use a pressure cooker for cooking to save energy and time.\n";
            tips += "- Reduce water heater usage by washing clothes in cold water.\n";
            tips += "- Seal gaps and cracks in your home's exterior to prevent air leakage.\n";
            tips += "- Use a drying rack or clothesline instead of a dryer.\n";
            tips += "- Set your computer to sleep or hibernate mode when not in use.\n";
            tips += "- Use a toaster oven for small cooking tasks instead of the oven.\n";
            tips += "- Replace old, inefficient appliances with ENERGY STAR models.\n";
        } else if (predictedBill > 4000) {
            tips += "- Opt for energy-efficient lighting, such as LED or CFL bulbs.\n";
            tips += "- Use a programmable thermostat for optimized temperature settings.\n";
            tips += "- Turn off lights and electronics in unoccupied rooms.\n";
            tips += "- Seal and insulate ducts to improve HVAC efficiency.\n";
            tips += "- Choose energy-efficient models when purchasing new appliances.\n";
            tips += "- Replace worn weatherstripping around doors and windows.\n";
            tips += "- Install a high-efficiency HVAC system for heating and cooling.\n";
            tips += "- Use natural ventilation and fans instead of air conditioning.\n";
            tips += "- Unplug chargers and devices when fully charged or not in use.\n";
            tips += "- Set your water heater to a lower temperature setting.\n";
            tips += "- Take advantage of natural sunlight during the day.\n";
            tips += "- Use a power strip to easily turn off multiple devices.\n";
            tips += "- Wash clothes with cold water to save energy.\n";
            tips += "- Reduce water usage by fixing leaks and using low-flow fixtures.\n";
            tips += "- Insulate your home to prevent heat loss during winter.\n";
        } else {
            tips += "";
        }
        return tips;
    }
}
